### ISSUE TITLE
Move to Unitful

### ISSUE THREAD

**Issue by tlnagy** [JuliaIO/NRRD.jl#6]
@timholy Is the plan to move NRRD.jl over to using Unitful.jl over SIUnits.jl?

**Comment by timholy** [comment]
Already done, try out the `images-next` branch.

**Comment by timholy** [comment]
FYI we had at least one problem with our interpretation of the NRRD format; that's fixed on the branch, but it's also possible that it won't read some of our formerly-produced files. NRRD lacks a test suite (big problem), but recently I discovered `unu make` which can generate valid headers, so I'm more confident that we're using the "standard" correctly.

Details: https://sourceforge.net/p/teem/bugs/14/

**Comment by tlnagy** [comment]
Yeah, hopefully they'll nail down the format a bit more. I think I'll probably have to move to OME-TIFF though, until https://github.com/micro-manager/micro-manager/issues/446 gets fixed (if ever).

**Comment by timholy** [comment]
Fixed in #7
